project:
  type: website
  output-dir: docs

website:
  title: "Kyle McFarren - UIC MSCA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd
      - current courses.qmd
      - previous courses.qmd

format:
  html:
    theme: spacelab
    mainfont: arial
    fontsize: .85rem
    fontcolor: "#7F5858"
    linkcolor: "#ff33f0"
    monofont: courier new
    css: styles.css
    toc: true

editor: visual
